#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
plot_departure.py

Inputs (generated by your pipeline):
  - departure_logs_lam_XXXX.npz  (decision-only logs)
  - summary_lam_XXXX.json        (optional; for sanity/extra stats)

Outputs:
  - plots/dep_curves_lam_XXXX.png
  - plots/dep_events_lam_XXXX.png
  - plots/dep_summary.csv
  - plots/dep_summary_from_json.csv  (if summary json exists)

Usage:
  python3 plot_departure.py --run_dir ./runs_mnl/exp1 --window 200
  python3 plot_departure.py --run_dir ./runs_mnl/exp1 --lam 50.0 --window 500 --show
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np


def _parse_lam_from_name(p: Path) -> Optional[float]:
    # departure_logs_lam_0.0000.npz
    m = re.search(r"lam_([0-9]+(?:\.[0-9]+)?)", p.name)
    if m is None:
        return None
    try:
        return float(m.group(1))
    except Exception:
        return None


def _safe_mean(x: np.ndarray) -> float:
    x = np.asarray(x, dtype=np.float64)
    return float(x.mean()) if x.size > 0 else float("nan")


def _safe_tail_mean(x: np.ndarray, tail_frac: float = 0.2) -> float:
    x = np.asarray(x, dtype=np.float64)
    if x.size == 0:
        return float("nan")
    n_tail = max(1, int(np.ceil(x.size * float(tail_frac))))
    return float(x[-n_tail:].mean())


def _rolling_mean(y: np.ndarray, w: int) -> np.ndarray:
    y = np.asarray(y, dtype=np.float64)
    if w <= 1:
        return y
    if y.size < w:
        return np.asarray([], dtype=np.float64)
    kernel = np.ones(w, dtype=np.float64) / float(w)
    return np.convolve(y, kernel, mode="valid")


def _rolling_with_x(x: np.ndarray, y: np.ndarray, w: int) -> Tuple[np.ndarray, np.ndarray]:
    x = np.asarray(x, dtype=np.int64)
    y = np.asarray(y, dtype=np.float64)
    if y.size == 0:
        return np.asarray([], dtype=np.int64), np.asarray([], dtype=np.float64)
    if w <= 1:
        return x, y
    if y.size < w:
        return np.asarray([], dtype=np.int64), np.asarray([], dtype=np.float64)
    y_ma = _rolling_mean(y, w)
    x_ma = x[w - 1 :]
    return x_ma, y_ma


def _load_npz(npz_path: Path) -> Dict[str, np.ndarray]:
    d = np.load(npz_path, allow_pickle=False)
    out = {k: d[k] for k in d.files}
    return out


def _maybe_load_summary_json(run_dir: Path, lam: float) -> Optional[Dict]:
    p = run_dir / f"summary_lam_{lam:.4f}.json"
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return None


def _ensure_dir(p: Path):
    p.mkdir(parents=True, exist_ok=True)


def find_departure_npz(run_dir: Path, lam: Optional[float] = None) -> List[Tuple[float, Path]]:
    files = sorted(run_dir.glob("departure_logs_lam_*.npz"))
    out: List[Tuple[float, Path]] = []
    for f in files:
        v = _parse_lam_from_name(f)
        if v is None:
            continue
        if lam is not None and abs(v - float(lam)) > 1e-9:
            continue
        out.append((float(v), f))
    out.sort(key=lambda t: t[0])
    return out


def plot_one(
    lam: float,
    npz_path: Path,
    out_dir: Path,
    window: int,
    tail_frac: float,
    show: bool,
):
    # matplotlib import은 여기서 (headless 대응)
    import matplotlib
    if not show:
        matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    logs = _load_npz(npz_path)

    dep_prob_router = np.asarray(logs.get("dep_prob_router", []), dtype=np.float64)
    dep_evt_router = np.asarray(logs.get("dep_event_router", []), dtype=np.float64)
    dep_step_router = np.asarray(logs.get("dep_step_router", []), dtype=np.int64)

    dep_prob_star = np.asarray(logs.get("dep_prob_star", []), dtype=np.float64)
    dep_step_star = np.asarray(logs.get("dep_step_star", []), dtype=np.int64)

    # rolling
    xr, pr_ma = _rolling_with_x(dep_step_router, dep_prob_router, window)
    xs, ps_ma = _rolling_with_x(dep_step_star, dep_prob_star, window)
    xr2, er_ma = _rolling_with_x(dep_step_router, dep_evt_router, window)

    # ----- Plot 1: expected dep curves -----
    plt.figure()
    if xr.size > 0:
        plt.plot(xr, pr_ma, label=f"Router E[dep] MA(w={window})")
    else:
        plt.plot(dep_step_router, dep_prob_router, label="Router E[dep] (raw)")
    if xs.size > 0:
        plt.plot(xs, ps_ma, label=f"Oracle@queue-max E[dep*] MA(w={window})")
    else:
        if dep_prob_star.size > 0:
            plt.plot(dep_step_star, dep_prob_star, label="Oracle@queue-max E[dep*] (raw)")

    plt.xlabel("step index")
    plt.ylabel("departure probability")
    plt.title(f"Departure (expected) | lam={lam:.4f}")
    plt.legend()
    plt.tight_layout()
    fig1 = out_dir / f"dep_curves_lam_{lam:.4f}.png"
    plt.savefig(fig1, dpi=200)
    if show:
        plt.show()
    plt.close()

    # ----- Plot 2: event dep curve (0/1) -----
    plt.figure()
    if xr2.size > 0:
        plt.plot(xr2, er_ma, label=f"Router departed(0/1) MA(w={window})")
    else:
        plt.plot(dep_step_router, dep_evt_router, label="Router departed(0/1) (raw)")
    plt.xlabel("step index")
    plt.ylabel("departed (moving avg)")
    plt.title(f"Departure (event) | lam={lam:.4f}")
    plt.legend()
    plt.tight_layout()
    fig2 = out_dir / f"dep_events_lam_{lam:.4f}.png"
    plt.savefig(fig2, dpi=200)
    if show:
        plt.show()
    plt.close()

    # ----- Stats for CSV -----
    row = {
        "lam_cost": lam,
        "n_router_logged": int(dep_prob_router.size),
        "n_star_logged": int(dep_prob_star.size),
        "dep_router_mean": _safe_mean(dep_prob_router),
        "dep_router_tail_mean": _safe_tail_mean(dep_prob_router, tail_frac=tail_frac),
        "dep_router_event_mean": _safe_mean(dep_evt_router),
        "dep_star_mean": _safe_mean(dep_prob_star),
        "dep_star_tail_mean": _safe_tail_mean(dep_prob_star, tail_frac=tail_frac),
    }
    return row, str(fig1), str(fig2)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run_dir", type=str, required=True, help="runs directory (e.g., ./runs_mnl/exp1)")
    ap.add_argument("--lam", type=float, default=None, help="optional: plot only specific lam")
    ap.add_argument("--window", type=int, default=200, help="moving average window (decision-only series)")
    ap.add_argument("--tail_frac", type=float, default=0.2, help="tail fraction for tail mean")
    ap.add_argument("--out_dir", type=str, default=None, help="output directory (default: <run_dir>/plots)")
    ap.add_argument("--show", action="store_true", help="show plots (also saves)")
    args = ap.parse_args()

    run_dir = Path(args.run_dir)
    if not run_dir.exists():
        raise FileNotFoundError(f"run_dir not found: {run_dir}")

    out_dir = Path(args.out_dir) if args.out_dir is not None else (run_dir / "plots")
    _ensure_dir(out_dir)

    items = find_departure_npz(run_dir, lam=args.lam)
    if len(items) == 0:
        raise FileNotFoundError(f"no departure_logs_lam_*.npz found in {run_dir}")

    summary_rows: List[Dict] = []
    json_rows: List[Dict] = []

    for lam, npz_path in items:
        row, fig1, fig2 = plot_one(
            lam=lam,
            npz_path=npz_path,
            out_dir=out_dir,
            window=int(args.window),
            tail_frac=float(args.tail_frac),
            show=bool(args.show),
        )
        summary_rows.append(row)

        sj = _maybe_load_summary_json(run_dir, lam)
        if isinstance(sj, dict):
            json_rows.append(sj)

        print(f"[OK] lam={lam:.4f} -> {Path(fig1).name}, {Path(fig2).name}")

    # save dep_summary.csv (from npz logs)
    import pandas as pd
    df = pd.DataFrame(summary_rows).sort_values("lam_cost").reset_index(drop=True)
    df.to_csv(out_dir / "dep_summary.csv", index=False)
    print(f"[Saved] {out_dir / 'dep_summary.csv'}")

    # save dep_summary_from_json.csv (optional)
    if len(json_rows) > 0:
        dfj = pd.DataFrame(json_rows)
        # 흔히 필요한 컬럼만 우선 정리
        cols = [
            "lam_cost",
            "avg_regret", "final_Q_gap", "explore_rate", "cnt_decision",
            "dep_router_mean", "dep_router_tail20_mean", "dep_router_event_mean",
            "dep_star_mean", "dep_star_tail20_mean",
            "dep_oracle_mean", "dep_oracle_event_mean",
            "n_router_decisions_logged", "n_star_snapshots_logged",
        ]
        keep = [c for c in cols if c in dfj.columns]
        dfj = dfj[keep].sort_values("lam_cost").reset_index(drop=True)
        dfj.to_csv(out_dir / "dep_summary_from_json.csv", index=False)
        print(f"[Saved] {out_dir / 'dep_summary_from_json.csv'}")


if __name__ == "__main__":
    main()
